variables:
  DOCKER_IMAGE: "python:3.12-slim"

stages:
  - test

test-job:
  stage: test
  image: $DOCKER_IMAGE
  script:
    - pip install -e .
    - book-tool -h
    - echo "Ready!"
  only:
    - main
